swim_log/main/routes.py
from flask import Blueprint, render_template, request, abort
from swim_log.models import Session, User
from flask_login import login_required, current_user


main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home():
    return render_template('home.html', title='Home', legend='home')


@main.route("/dashboard")
@login_required
def dashboard():
    user = User.query.filter_by(username=current_user.username).first_or_404()
    totalSwims = Session.query.filter_by(swimmer=user).count()
    sessions = Session.query.filter_by(swimmer=user)
    totalTime = 0
    for session in sessions:
        totalTime += session.swim_time
    freestyleCount = Session.query.filter_by(swimmer=user, swim_stroke='Freestyle').count()
    backstrokeCount = Session.query.filter_by(swimmer=user, swim_stroke='Backstroke').count()
    breaststrokeCount = Session.query.filter_by(swimmer=user, swim_stroke='Breaststroke').count()
    butterflyCount = Session.query.filter_by(swimmer=user, swim_stroke='Butterfly').count()
    return render_template('dashboard.html', title='Dashboard', totalSwims=totalSwims, totalTime=totalTime, freestyleCount=freestyleCount, backstrokeCount=backstrokeCount, breaststrokeCount=breaststrokeCount, butterflyCount=butterflyCount, user=user)


@main.route("/history/<string:username>")
@login_required
def history(username):
    if username != current_user.username:
        abort(403)
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    sessions = Session.query.filter_by(swimmer=user).order_by(Session.session_date.desc()).paginate(page=page, per_page=10)
    return render_template('history.html', title='History', sessions=sessions, user=user)

swim_log/users/routes.py
from flask import Blueprint
from flask import render_template, url_for, flash, redirect, request
from swim_log import db, bcrypt
from swim_log.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from swim_log.models import User
from flask_login import login_user, current_user, logout_user, login_required
from swim_log.users.utils import save_picture, send_reset_email


users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created - you may now login.', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Registration', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.dashboard'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.dashboard'))
        else:
            flash('Login unsuccessful, please check email and password.', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated.', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account', form=form, image_file=image_file)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.dashboard'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions on how to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.dashboard'))
    user = User.verify_reset_token(token)
    if User is None:
        flash('That is an invalid or expired token.', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated - you may now login.', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

swim_log/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>About Page</h1>
{% endblock content %}

swim_log/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="card w3-animate-opacity">
        <div class="card-body">
            <div class="media">
                <img class="rounded-circle account-img" src="{{ image_file }}">
                <div class="media-body">
                    <h2 class="account-heading">{{ current_user.username }}</h2>
                    <p class="text-secondary">{{ current_user.email }}</p>
                </div>
            </div>
            <form method="POST" action="" enctype="multipart/form-data">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Account Information</legend>
                    <div class="form-group">
                        {{ form.username.label(class="form-control-label") }}

                        <!-- Error control -->
                        {% if form.username.errors %}
                            {{ form.username(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.username.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.username(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.email.label(class="form-control-label") }}

                        <!-- Error control -->
                        {% if form.email.errors %}
                            {{ form.email(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.email(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.picture.label() }}
                        {{ form.picture(class="form-control-file") }}
                        {% if form.picture.errors %}
                            {% for error in form.picture.errors %}
                                <span class="text-danger">{{ error }}</span></br>
                            {% endfor %}
                        {% endif %}
                    </div>
                </fieldset>
                <div class="form-group">
                    {{ form.submit(class="btn btn-outline-info") }}
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

swim_log/templates/add_swim.html
{% extends "layout.html" %}
{% block content %}
    <h1>Add Swim</h1>
{% endblock content %}

swim_log/templates/dashboard.html
{% extends "layout.html" %}
{% block content %}
    <h1>Dashboard</h1><hr>
    <div class="row">
        <div class="col">
            <div class="card w3-animate-opacity">
                <div class="card-body">
                    <center><u><h5 class="card-title">Total Swims:</h5></u></center>
                    <center><h4>{{ totalSwims }}</h4></center>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card w3-animate-opacity">
                <div class="card-body">
                    <center><u><h5 class="card-title">Total Time:</h5></u></center>
                    <center><h4>{{ totalTime }} seconds</h4></center>
                </div>
            </div>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col">
            <div class="card w3-animate-opacity">
                <div class="card-body">
                    <center><u><h5 class="card-title">Swim Sessions (Grouped by Stroke):</h5></u></center>
                    <canvas id="sessionCounts"></canvas>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0/dist/Chart.min.js"></script>
    <script>
        var ctx = 'sessionCounts';
        var sessionCounts = new Chart(ctx, {
            type: 'pie',
            data: {
                labels: ['Freestyle', 'Backstroke', 'Breaststroke', 'Butterfly'],
                datasets: [{
                    label: 'Sessions',
                    data: [{{ freestyleCount }}, {{ backstrokeCount }}, {{ breaststrokeCount }}, {{ butterflyCount }}],
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)'
                    ],
                    borderColor: [
                        'rgba(255, 99, 132, 1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)'
                    ],
                    borderWidth: 1
                }]
            }
        });
    </script>
{% endblock content %}

swim_log/templates/history.html
{% extends "layout.html" %}
{% block content %}
    <h1>History</h1><hr>
    {% if not sessions.items %}
        <p>Looks like you haven't logged any swims yet - <a href="{{ url_for('sessions.log_swim') }}">get to it!</a></p>
    {% else %}
        <div class="card w3-animate-opacity">
            <div class="card-body">
                <table class="table">
                    <thead class="thead-light">
                        <tr>
                            <th>Date</th>
                            <th>Swim Type</th>
                            <th>Stroke</th>
                            <th>Distance (in yards)</th>
                            <th>Time (in seconds)</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for session in sessions.items %}
                            <tr>
                                <th scope="row"><a href="{{ url_for('sessions.session', session_id=session.id) }}">{{ session.session_date }}</a></th>
                                <td>{{ session.swim_type }}</td>
                                <td>{{ session.swim_stroke }}</td>
                                <td>{{ session.swim_distance }}</td>
                                <td>{{ session.swim_time }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <br>
        <center>
        {% for page_num in sessions.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if page_num %}
                {% if sessions.page == page_num %}
                        <a class="btn btn-info mb-4" href="{{ url_for('main.history', username=user.username, page=page_num) }}">{{ page_num }}</a>
                {% else %}
                        <a class="btn btn-outline-info mb-4" href="{{ url_for('main.history', username=user.username, page=page_num) }}">{{ page_num }}</a>
                {% endif %}
            {% else %}
                ...
            {% endif %}
        {% endfor %}
        </center>
    {% endif %}
{% endblock content %}

swim_log/templates/home.html
{% extends "layout.html" %}
{% block content_home %}
    <div class="jumbotron" style="margin-top:-2em; background-color:#dee3e8">
        <div class="container">
            <h1 class="display-3">Start Logging!</h1>
            <p><strong>Swimming is tough.</strong> Keeping track of your swimming progress is even tougher. Over 50% of solo swimmers don't track their swimming history and suffer painstakingly slow progress and decreased motivation as a result. Register today and take the grunt work out of the equation by logging your swims with Swim Log!</p>
            <p><a class="btn btn-primary btn-lg" href="{{ url_for('users.register') }}" role="button">Register &raquo;</a></p>
        </div>
    </div>

    <div class="container">
        <!-- Example row of columns -->
        <div class="row">
            <div class="col-md-4">
                <h2>Tracking</h2>
                <p>View every swim that you've ever logged simply by navigating to your history. See the distances, strokes, dates, times and other information about any and every swim you've ever tracked. This is our bread and butter!</p>
              </div>
            <div class="col-md-4">
                <h2>Analytics</h2>
                <p>Are you curious what strokes you swim the most? How about the amount of time you've spent in the pool? Maybe you want to know how many sessions you've ever logged. You can view these analytics and more on your Dashboard!</p>
            </div>
            <div class="col-md-4">
                <h2>Simple UI</h2>
                <p>We get it - you just want to see what you need to make progress. By avoiding unnecessary features, the Swim Log team has managed to keep a clean, simple UI that only shows you what you need to get to the other side of the pool faster.</p>
            </div>
        </div>
    </div>
{% endblock content_home %}

swim_log/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Styling -->
    <link rel="icon" href="{{ url_for('static', filename='img/favicon.ico') }}?v=2" type="image/x-icon" />
    <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <style>
      .footer {
        position: absolute;
        bottom: 0;
        width: 100%;
        height: 80px; /* Set the fixed height of the footer here */
        line-height: 60px; /* Vertically center the text there */
        background-color: #f5f5f5;
      }

      body {
        background-color: #EEEEEE;
        padding-top: 5rem;
        margin-bottom: 100px; /* Margin bottom by footer height */
      }

      html {
        position: relative;
        min-height: 100%;
      }

      a.nav-link {
        transition:.2s;
      }
    </style>
    <!-- Title -->
    {% if title %}
        <title>Swim Log | {{ title }} </title>
    {% else %}
        <title>Swim Log</title>
    {% endif %}
</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="#"><i class="fas fa-fish" style="color:#dee3e8"></i> <strong style="color:#dee3e8">Swim Log</strong></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <!-- Left navigation -->
      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          {% if not current_user.is_authenticated %}
          <li class="nav-item">
            <a id="home" class="nav-link {% if title=='Home' %}active{% endif %}" href="{{ url_for('main.home') }}"><i class="fas fa-home"></i> Home</a>
          </li>
          {% endif %}
          {% if current_user.is_authenticated %}
          <li class="nav-item">
            <a id="dashboard" class="nav-link {% if title=='Dashboard' %}active{% endif %}" href="{{ url_for('main.dashboard') }}"><i class="fas fa-tachometer-alt"></i> Dashboard</a>
          </li>
          {% endif %}
          {% if current_user.is_authenticated %}
          <li class="nav-item">
            <a id="history" class="nav-link {% if title=='History' %}active{% endif %}" href="{{ url_for('main.history', username=current_user.username) }}"><i class="fas fa-history"></i> History</a>
          </li>
          {% endif %}
        </ul>
        <ul class="navbar-nav ml-auto">
          {% if current_user.is_authenticated %}
          <li class="nav-item">
            <a id="log_swim" class="nav-link {% if title=='Add Swim' %}active{% endif %}" href="{{ url_for('sessions.log_swim') }}"><i class="fas fa-plus-circle"></i> Add Swim</a>
          </li>
          <li class="nav-item">
            <a id="account" class="nav-link {% if title=='Account' %}active{% endif %}" href="{{ url_for('users.account') }}"><i class="fas fa-user-circle"></i> Account</a>
          </li>
          <li class="nav-item">
            <a id="logout" class="nav-link" href="{{ url_for('users.logout') }}"><i class="fas fa-sign-out-alt"></i> Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a id="login" class="nav-link {% if title=='Login' %}active{% endif %}" href="{{ url_for('users.login') }}"><i class="fas fa-sign-in-alt"></i> Login</a>
          </li>
          <li class="nav-item">
            <a id="register" class="nav-link {% if title=='Registration' %}active{% endif %}" href="{{ url_for('users.register') }}"><i class="fas fa-user-check"></i> Register</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <!-- Content block -->
    {% if legend == 'home' %}
      {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
              {% for category, message in messages %}
                  <div class="alert alert-{{ category }}">
                      {{ message }}
                  </div>
              {% endfor %}
          {% endif %}
      {% endwith %}
      {% block content_home %}{% endblock content_home %}
    {% else %}
      <div class="container">
          {% with messages = get_flashed_messages(with_categories=true) %}
              {% if messages %}
                  {% for category, message in messages %}
                      <div class="alert alert-{{ category }}">
                          {{ message }}
                      </div>
                  {% endfor %}
              {% endif %}
          {% endwith %}
          {% block content %}{% endblock content %}
      </div>
    {% endif %}
    <footer class="footer">
      <div class="container">
        <p class="float-right">
          <a href="#top">Back to top</a>
        </p>
        <span class="text-muted">&copy; David Salazkin</span>
      </div>
    </footer>

    <!-- Javascript -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <script>
      $(document).ready(function () {
      $("#{{request.endpoint}}").parent().addClass("active"); })
    </script>
</body>
</html>

swim_log/templates/log_swim.html
{% extends "layout.html" %}
{% block content %}
    <h1>{{ legend }}</h1><hr>
    <div class="card w3-animate-opacity">
        <div class="card-body">
            <form method="POST" action="">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <div class="form-group">
                        {{ form.session_date.label(class="form-control-label") }}

                        <!-- Error control -->
                        {% if form.session_date.errors %}
                            {{ form.session_date(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.session_date.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.session_date(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <!-- Swim -->
                    </br><h3>Swim</h3><hr>
                    <div class="row">
                        <div class="col"">
                            <div class="form-group">
                                {{ form.swim_type.label(class="form-control-label") }}

                                <!-- Error control -->
                                {% if form.swim_type.errors %}
                                    {{ form.swim_type(class="form-control form-control-lg is-invalid") }}
                                    <div class="invalid-feedback">
                                        {% for error in form.swim_type.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ form.swim_type(class="form-control form-control-lg") }}
                                {% endif %}
                                <small id="emailHelp" class="form-text text-muted"><a href="#">Learn about the options in this field.</a></small>
                            </div>
                        </div>
                        <div class="col">
                            <div class="form-group">
                                {{ form.swim_stroke.label(class="form-control-label") }}

                                <!-- Error control -->
                                {% if form.swim_stroke.errors %}
                                    {{ form.swim_stroke(class="form-control form-control-lg is-invalid") }}
                                    <div class="invalid-feedback">
                                        {% for error in form.swim_stroke.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ form.swim_stroke(class="form-control form-control-lg") }}
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="form-group">
                                {{ form.swim_distance.label(class="form-control-label") }}

                                <!-- Error control -->
                                {% if form.swim_distance.errors %}
                                    {{ form.swim_distance(class="form-control form-control-lg is-invalid") }}
                                    <div class="invalid-feedback">
                                        {% for error in form.swim_distance.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ form.swim_distance(class="form-control form-control-lg") }}
                                {% endif %}
                            </div>
                        </div>
                        <div class="col">
                            <div class="form-group">
                                {{ form.swim_time.label(class="form-control-label") }}

                                <!-- Error control -->
                                {% if form.swim_time.errors %}
                                    {{ form.swim_time(class="form-control form-control-lg is-invalid") }}
                                    <div class="invalid-feedback">
                                        {% for error in form.swim_time.errors %}
                                            <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ form.swim_time(class="form-control form-control-lg") }}
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    </div>
                </fieldset>
                <div class="form-group">
                    <center>{{ form.submit(class="btn btn-outline-info") }}</center>
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

swim_log/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="card w3-animate-opacity">
        <img src="{{ url_for('static', filename='img/login.png') }}" class="card-img-top">
        <div class="card-body">
            <form method="POST" action="">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <div class="form-group">
                        {{ form.email.label(class="form-control-label") }}

                        <!-- Error control -->
                        {% if form.email.errors %}
                            {{ form.email(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.email(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.password.label(class="form-control-label") }}

                        <!-- Error control -->
                        {% if form.password.errors %}
                            {{ form.password(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.password.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.password(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-check">
                        {{ form.remember(class="form-check-input") }}
                        {{ form.remember.label(class="form-check-label") }}
                    </div>
                </fieldset>
                <div class="form-group">
                    {{ form.submit(class="btn btn-outline-info") }}
                    <small class="text-muted ml-2">
                        <a href="{{ url_for('users.reset_request') }}">Forgot password?</a>
                    </small>
                </div>
            </form>
            <div class="border-top pt-3">
                <small class="text-muted">
                    Don't already have an account? <a class="ml-2" href="{{ url_for('users.register') }}">Register</a>
                </small>
            </div>
        </div>
    </div>
{% endblock content %}

swim_log/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
    <h1>Reset Password</h1><hr>
    <div class="card w3-animate-opacity">
        <div class="card-body">
            <form method="POST" action="">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <div class="form-group">
                        {{ form.email.label(class="form-control-label") }}

                        <!-- Error control -->
                        {% if form.email.errors %}
                            {{ form.email(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.email(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                </fieldset>
                <div class="form-group">
                    {{ form.submit(class="btn btn-outline-info") }}
                </div>
            </form>
        </div>
    </div>
{% endblock content %}